parser/src/earley/parser.rs

Add comment to scan()

---

parser/src/earley/parser.rs

Add comments to parser.rs

---

parser/src/earley/parser.rs

Comment for just_add() in parser.rs

Comment for just_add() in parser.rs

---

parser/src/earley/parser.rs

Rearrange Kallmeyer 2018 biblio entry

Biblio rearrangment in parser.rs

---

parser/src/earley/parser.rs

Add comments on agenda processing

Add comments on agenda processing

---

parser/src/earley/parser.rs

Two comments for parser.rs

---

parser/src/earley/parser.rs

Comment in parser.rs

---

parser/src/earley/parser.rs

Comment about 'maxtokens' in parser.rs

Comment about 'maxtokens' in parser.rs

---

parser/src/earley/parser.rs

Mark hidden stuff as deprecated

Mark hidden stuff as deprecated

---

parser/src/earley/parser.rs

Fill out comments on scan() in parser.rs

Fill out comments on scan() in parser.rs

---

parser/src/earley/parser.rs

Comment on code to "advance" parse

Comment on code to "advance" parse

---

parser/src/earley/parser.rs

Various comments in parser.rs

---

parser/src/earley/parser.rs

Add comments about the lexer stack in parser.rs.

Add comments about the lexer stack in parser.rs

---

parser/src/earley/parser.rs

Comments about "hidden" and the Recogizer trait in parser.rs.

Comments about "hidden" and the Recogizer trait in parser.rs

---

parser/README.md

Fix typos in README.md

---

parser/src/earley/parser.rs

Comment on try_push_byte() in parser.rs.

Comment on try_push_byte() in parser.rs

---

parser/src/earley/parser.rs
rust/src/py.rs

Comments re the LLM interface.

Comments re LLM interface

---

parser/src/earley/parser.rs

Comment on collapse() method

---

parser/src/earley/parser.rs

Refine comment on speculative vs. definitive.

Refine comment on speculative vs. definitive

---

parser/src/lib.rs

Add per-file comment to lib.rs.

Add per-file comment to lib.rs

---

parser/Cargo.toml

add "cdylib" to parser binary, so user can choose which to use

Add cdylib crate type to parser

---

parser/src/grammar_builder.rs

Comment counted segment logic.

Comment counted segment logic

---

parser/src/earley/parser.rs
parser/src/tokenparser.rs

Comment on call stack for committing tokens.

Comment on call stack for committing tokens

---

parser/src/earley/parser.rs

Work on comment for advance_parser().

Work on comment for advance_parser()

---

parser/src/earley/parser.rs

Comment on single byte lexemes.

Comment on single byte lexemes

---

parser/src/earley/parser.rs

Comments on virtual Earley stack and forced bytes.

Comments on virtual Earley stack and forced bytes

---

parser/src/earley/regexvec.rs

Add comments on regex vectors.

Comments on regex vectors

---

parser/src/earley/regexvec.rs

Comments on lowest_match_inner().

Comments on lowest_match_inner()

---

parser/src/json/compiler.rs
python/llguidance/_lib.pyi
rust/src/py.rs

Adds `coerce_one_of` option (false by default)

Do not treat oneOf as anyOf by default

---

parser/src/json/schema.rs

fix some test issues with prefixItems

[Bug] Treat schema's own items as pseudo-prefixItems when merging

---

parser/src/json/schema.rs

Check for presence of any *keyword* that is not listed in META_AND_ANNOTATIONS, not any *key*

---

parser/llguidance.h
parser/src/api.rs
parser/src/ffi.rs
parser/src/matcher.rs
scripts/cbindgen.sh
toktrie/src/toktree.rs

expose Matcher interface in C

---

parser/src/json/compiler.rs
parser/src/json/numeric.rs
parser/src/json/schema.rs

Creates types for ObjectSchema, ArraySchema etc so they can be passed around as one thing, not split into arguments.

refactor Schema AST

---

docs/json_schema.md
json_stats/expected_maskbench.json
parser/src/earley/from_guidance.rs
parser/src/earley/lexerspec.rs
parser/src/earley/parser.rs
parser/src/ffi.rs
parser/src/grammar_builder.rs
parser/src/json/compiler.rs
parser/src/json/schema.rs
parser/src/json/shared_context.rs
parser/src/matcher.rs
parser/src/tokenparser.rs
python/llguidance/_lib.pyi
python/torch_tests/test_matcher.py
python_ext/src/llmatcher.rs
sample_parser/tests/test_lark.rs
scripts/test-guidance.sh

This also re-works the Python API for warnings (was unreleased) to be more ergonomic

support for patternProperties in JSON schema

---

docs/json_schema.md
json_stats/expected_maskbench.json
json_stats/src/json_stats.rs
parser/src/json/compiler.rs
parser/src/json/schema.rs
sample_parser/tests/test_lark.rs

support for min/maxProperties

---

python/llguidance/llamacpp.py
python/torch_tests/test_hf.py
python/torch_tests/test_llamacpp.py
python_ext/src/py.rs
scripts/install-deps.sh

@hudson-ai let me know if the API looks good for you!

native llama.cpp tokenizer support

---

docs/de_recursing.md

Partially in response to #198 , add a small cook book for removing recursion from grammars.

[Doc] Add De-Recursion Cook book

---

sample_parser/tests/common_lark_utils/mod.rs
sample_parser/tests/test_json_arrays.rs
sample_parser/tests/test_json_objects.rs
sample_parser/tests/test_json_primitives.rs

Begin porting the JSON tests over from Python, since they really belong here.
Have had to add some clippy suppressions for reasons which escape me.

[Test] Start porting JSON tests

---

.github/workflows/code-coverage.yml

Extending the code coverage workflow with a separate job running the Python tests

[Build] Run code coverage from Python
