guidance-ai/llguidance

- parser/src/earley/parser.rs
> Add comments to parser.rs

- python/llguidance/_lib.pyi
- rust/src/py.rs
Note: This is helpful to integrate llguidance into inference frameworks that do not support backtracking atm.
> Add args to enable/disable backtracking and fast-forwarding in LLInterpreter

- parser/src/tokenparser.rs
Follow advance_parser() calls in comments (tokenparser.rs).
> Follow advance_parser() calls in comments (tokenparser.rs)

- parser/src/constraint.rs
Trace advance_parser() calls in comments.
> Trace advance_parser() calls in comments

- parser/src/json/compiler.rs
- parser/src/json/schema.rs
Re-writes consts as other types, e.g. arrays with specific prefixItems, ints with minimum==maximum, etc. Enums are then written as anyOf(consts).
This lets us use our internal validation logic rather than relying on jsonschema.
Note: I also fixed the grammar-builder's handling of UnsatisfiableSchemaError in anyOf -- it now appropriately propagates only when there are no valid schemas.
> Remove need for JSON validator for consts and enums

- python/llguidance/_lib.pyi
The signature of JsonCompiler in the .pyi was wrong.
@lochuynh1412 fyi
> fix the pyi to reflect the correct signature of JsonCompiler

- parser/Cargo.lock
- parser/Cargo.toml
- parser/src/json/numeric.rs
Ports the numeric range tests we're currently doing in python into the crate. Found some bugs and fixed them.
> Add tests for numeric regular expressions; some bug fixes

- python/llguidance/__init__.py
- python/llguidance/_lib.pyi
- rust/src/py.rs
Adds `LarkCompiler` and `RegexCompiler` to the python API. Also changes the `JsonCompiler` slightly such that it returns a `TopLevelGrammar` rather than a `GrammarWithLexer` node, such that the output is "ready to consume" by an `LLInterpreter`.
@lochuynh1412 should make your life easier!
> Add lark and regex compilers to the python API

- parser/src/grammar_builder.rs
- sample_parser/Cargo.lock
- For the FHIR schema, all the serialization calls slow things down by about 15%, (from ~140ms to build the whole grammar to ~160ms)
- For the FHIR schema, this decreases the size of the compiled grammar by about 30%
- I have concerns about storing serialized grammars as keys, as this should about double the size of our `GrammarBuilder` struct. But this is pretty inconsequential unless we're talking huge schemas like FHIR (and I suppose 2*.7=1.4 means we're not quite doubling the size overall)
There are likely quite a few optimizations we can still do to reduce the time to build grammars, both in the JSON compiler and in `repeat`.
Linked to issue #58
> Cache `NodeRef`s in `grammar_builder`

- parser/src/json/schema.rs
In particular, if a schema supplies `properties` and a `$ref` to another schema with properties, the properties in the root schema will be inserted first. This feels a bit more intuitive and is consistent with existing tests in guidance.
Ordering between the other applicators (`oneOf`, `anyOf`, `allOf`, and `$ref`) is still arbitrary -- may want to consider their order in the parent schema in the future (but this is beyond the scope of this PR)
> Prioritize base schema over schemas in oneOf, anyOf, allOf, and $ref

- parser/src/json/compiler.rs
Makes the following test pass:
```json
{
"description": "minLength validation",
"schema": {
"$schema": "https://json-schema.org/draft/2020-12/schema",
"minLength": 2
},
"tests": [
{
"description": "one grapheme is not long enough",
"data": "\uD83D\uDCA9",
"valid": false
}
]
}
```
> Treat UTF-16 surrogate pairs as single characters for string min/maxLength

- parser/src/json/schema.rs
> support for additionalItems

- Cargo.lock
- parser/Cargo.toml
- parser/src/grammar_builder.rs
- parser/src/json/compiler.rs
- parser/src/json/schema.rs
@mmoskal a few things here
1. I added a `add_ast` method to the `RegexBuilder` that will traverse a whole `derivre::RegexAst` and add it to the builder. This feels a little clunky, so I'd appreciate your thoughts.
2. I parsed the `pattern` and `format` into `RegexAst`s in `schema.rs` and intersected them early. `minLength` and `maxLength` did not get this treatment, as taking maximums/minimums of numbers feels like a cleaner way to intersect these.
3. To intersect `minLength` and `maxLength` with a regex, I had to do something mirroring what I did in my other open PR, namely using `"(?s:.{{{},{}}})"` with json-quoting rather than `"\"{}{{{},{}}}\""` with `CHAR_REGEX`.
4. The current state of this PR preserves all existing behaviors, but it does NOT yet actually allow intersecting …
> Intersect patterns, format, and min/maxLength

- parser/src/json/schema.rs
Adds a method to check for "verifiable" schema disjointness (returns false if we're not really sure) and uses it to coerce oneOf to anyOf whenever it is provably safe to do so. This includes cases where objects have required properties that are themselves provably disjoint, covering discriminated unions.
We could probably take this one step farther and actually compute the difference between some schemas (e.g. `Schema::Boolean.subtract(Schema::LiteralBoolean{ true }) => Schema::LiteralBoolean{ false }`), but simply checking for disjointness covers some important cases.
Closes (or at least contributes significant progress towards) #77
> Safe `oneOf`

- Cargo.lock
- json_stats/jstats.sh
- json_stats/scripts/xgr/xgr_combine.py
- json_stats/src/json_stats.rs
- parser/Cargo.toml
- parser/src/api.rs
- parser/src/earley/from_guidance.rs
- parser/src/grammar_builder.rs
- parser/src/json/compiler.rs
- parser/src/json/schema.rs
- parser/src/lark/compiler.rs
- sample_parser/tests/test_ll.rs
cc @hudson-ai for awareness; still WIP!
> compile strings etc as regexes

- Cargo.lock
- parser/Cargo.toml
- parser/src/api.rs
- parser/src/earley/from_guidance.rs
- parser/src/grammar_builder.rs
- parser/src/json/compiler.rs
- parser/src/json/numeric.rs
- parser/src/json/schema.rs
Uses new derivre `MultipleOf` functionality to support the JSON `multipleOf` assertion
TODOS:
> [JSON] `multipleOf`

- parser/src/json/compiler.rs
- parser/src/json/schema.rs
- python_ext/src/py.rs
Not high priority, but I think it's reasonable to allow users to pass custom retrievers if they want to resolve remote refs (we should NOT provide a default implementation of this though).
This also allows us to try more cases in the test suite, as we can just put all of the remote refs that the tests depend on into a HashMap which we thinly wrap with a Retrieve implementation.
I am very new to all this `dyn Trait` stuff, so I'm guessing I did something silly.
> [JSON] Allow custom retrievers

- docs/syntax.md
- parser/src/lark/parser.rs
allow passing string for capture_name to allow keys that may be illegal rule names
> Allow passing string for `capture_name` in lark syntax

- parser/src/earley/from_guidance.rs
- parser/src/json/compiler.rs
Exposes JsonCompileOptions under a key `x-guidance` in the top level of a JSON schema
> [JSON] "x-guidance" JsonCompileOptions

- python/llguidance/_tokenizer.py
- python_ext/src/py.rs
Guidance can avoid adding special bytes to the beginning of special tokens by providing a sequence of special token ids
> Identify special tokens via a sequence of special ids

- docs/json_schema.md
- json_stats/expected_maskbench.json
- json_stats/src/json_stats.rs
- parser/src/json/schema.rs
- parser/src/tokenparser.rs
The enforced property order during generation is as follows:
1. Each property in the `"properties"` object, in order of appearance
2. Each property in `"required"`, in order of appearance (if not already in `"properties"`)
When two schemas are joined (more than two is defined inductively), the resulting `"properties"` object will have order given by:
1. Each property in the left schema, in order of appearance
2. Each property in the right schema, in order of appearance (if not already in the left schema)
3. Recursive cases: 
- If the left schema defines a property that is also found in the right schema, the schema of the resulting merged property will be the result of merging the two properties with the same left,right precedence
- If the left schema defines a property NOT found in the …
> Stabilize property order

- docs/json_schema.md
- json_stats/expected_maskbench.json
- json_stats/src/json_stats.rs
- parser/llguidance.h
- parser/src/api.rs
- parser/src/earley/from_guidance.rs
- parser/src/earley/lexerspec.rs
- parser/src/earley/mod.rs
- parser/src/earley/parser.rs
- parser/src/ffi.rs
- parser/src/grammar_builder.rs
- parser/src/json/compiler.rs
- parser/src/json/schema.rs
- parser/src/json/shared_context.rs
- parser/src/matcher.rs
- parser/src/tokenparser.rs
- python/llguidance/_lib.pyi
- python/torch_tests/test_matcher.py
- python_ext/src/llmatcher.rs
- python_ext/src/py.rs
fixes #136
- add `x-guidance.lanient: true` to JSON Schema (generates warnings)
- add `warnings=true` parameter to `LLMatcher.validate_grammar()`; if set it may return "WARNING: ..."
- add `LLMatcher.get_grammar_warnings()` (for after the matcher is constructed)
- add warnings output to `llg_validate_grammar()`
> add lenient option to JSON schemas

- Cargo.lock
- toktrie_hf_tokenizers/Cargo.toml
The version of Oniguruma used in `onig_sys` doesn't build on GCC 15 and the oniguruma project itself got archived last week, so this PR switches tokenizers to the fancy-regex backend.
`fancy-regex` also requires flipping on the `unstable_wasm` feature until huggingface/tokenizers#1772 lands, that flag doesn't have any ill effects though since everything WASM related downstream is behind `target_arch` checks.
**tl;dr**: This fixes builds on Linux distros with newer GCC versions like Arch Linux and Fedora.
> use fancy-regex instead of onig as tokenizers regex library

- python/llguidance/_tokenizer.py
Make it the responsibility of the caller (`guidance`) to ensure proper tokenization under boundary effects (e.g. by removing leading space added by sentencepiece )
> Stop using prefix/sentinel strings for `TokenizerWrapper`

- python_ext/src/py.rs
We previously needed to manually clear the bytes for EOS to prevent them from appearing in model output, but it seems that this is no longer needed.
Fixes #177
> Keep EOS token bytes in `TokenizerWrapper`

- parser/src/tokenparser.rs
- python_ext/src/llinterpreter.rs
- python_ext/src/llmatcher.rs
- sample_parser/tests/test_ll.rs
This works for Python bindings only currently - include the offending grammar in error dump
> dump grammar in errors in LLInterpreter

- Cargo.lock
- toktrie_hf_tokenizers/Cargo.toml
- toktrie_hf_tokenizers/src/lib.rs
4 days ago huggingface released `tokenizers@v0.21.2`, which [changed the `get_normalizers` method to be an `impl AsRef<[NormalizerWrapper]> for Sequence`](https://github.com/huggingface/tokenizers/commit/c45aebd1029acfbe9e5dfe64e8b8441d9fae727a#diff-252dff06be81a9c396077c0b02f9f6aef6772058348bd6584031a48b351d623e). Due to the version requirement in `toktrie_hf_tokenizers` (`version = ">=0.20.0, <1.0.0"`), in the absence of a lockfile cargo fetches v0.21.2 which will not compile
This was caught in EricLBuehler/mistral.rs#1523
> fix: tokenizers normalizers sequence api changed

- docs/syntax.md
- parser/src/grammar_builder.rs
- parser/src/lark/compiler.rs
- sample_parser/tests/test_lark.rs
- sample_parser/tests/test_ll.rs
Proposes a syntax (`<[*]>`) to address #200, furthermore introduces token-class complements following semantics of regex character classes.
> Add lark syntax for "any token" and negation of token ranges

- parser/src/matcher.rs
- sample_parser/tests/test_raw_parser.rs
The bug: (found while debugging https://github.com/guidance-ai/llguidance/issues/211)
`try_consume_tokens` short-circuits when it finds an invalid token, missing the `inner.parser.check_stop` check and failing to put the parser into a stopped state. Subsequent calls to `try_consume_tokens` will always fail, and the parser is prevented from ever moving into a stopped state.
The fix:
Call `inner.parser.check_stop` in the short-circuit condition
> [Bug] `matcher.try_consume_tokens` not checking stop if some tokens are left unconsumed

- parser/src/tokenparser.rs
- sample_parser/tests/test_raw_parser.rs
Avoids `is_initialized` check (which causes an error state if the parser is stopped) in `validate_token` and `validate_tokens_raw` by checking whether the parser is stopped and returning early if so
Fixes #211
> [Bug] calling `try_consume_tokens` after parser is stopped causes error state

- CHANGELOG.md
- scripts/bump.py
Ensure links in the changelog include the "v".
Additionally update bump.py script to generate the correct format going forward
> [Cleanup] Fix links in CHANGELOG.md

- .github/workflows/code-coverage.yml
Adding a new GitHub workflow for code coverage, based on:
https://github.com/mozilla/grcov
For now, this creates an artifact containing the HTML coverage. Uploading to CodeCov (or similar) should also be possible.
> [Build] Add code coverage build

- sample_parser/tests/common_lark_utils/mod.rs
- sample_parser/tests/test_json_arrays.rs
- sample_parser/tests/test_json_enum_const.rs
- sample_parser/tests/test_json_primitives.rs
- sample_parser/tests/test_json_schema_combinations.rs
Having taken a look at code coverage, port some more of the Python-based JSON tests into the Rust layer. This includes tests for:
- prefixItems
- anyOf
- allOf
- multipleOf
- const
- enum
These are not as extensive as the Python tests, but will let some more issues get caught sooner.
> [Test] Extend JSON test coverage
